---
- name: Set up authorized keys for the root user
  authorized_key:
    user: root
    key: "{{ item }}"
  with_file:
    - tyrion

- name: present yum repo directory
  file:
    path: /etc/yum.repos.d/
    state: directory

- name: set centos7 yum repo to aliyun
  copy:
    src: CentOS-7.repo
    dest: /etc/yum.repos.d/CentOS-Base.repo
  # when:
  # - ansible_distribution | lower() == 'centos'
  # - ansible_distribution_major_version == '7'

- name: set centos7 epel repo
  copy:
    src: epel-7.repo
    dest: /etc/yum.repos.d/epel.repo
  # when:
  # - ansible_distribution | lower() == 'centos'
  # - ansible_distribution_major_version == '7'

- name: yum install package
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - net-tools

- name: yum update all
  yum:
    name: "*"
    state: latest
    update_cache: yes

- name: enable serial console
  copy:
    src: grub
    dest: /etc/default/grub

- name: re-generate grub
  shell: grub2-mkconfig -o /boot/grub2/grub.cfg

- name: enable and start serial-getty@ttyS0.service
  systemd:
    name: serial-getty@ttyS0.service
    enabled: yes
    state: started
  # when:
  # - ansible_distribution | lower() == 'centos'
  # - ansible_distribution_major_version == '7'
- name: Setup alternate SSH port
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    regexp: "^Port"
    line: "Port 2208"
  notify: "Restart sshd"